apiVersion: v1
kind: Service
metadata:
  name: store
spec:
  type: NodePort
  ports:
  - port: 8000
    name: http
    targetPort: http
  selector:
    team: tgedr
    project: microsvc-blueprint
    api: store
---
apiVersion: v1
kind: Service
metadata:
  name: solver
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    team: tgedr
    project: microsvc-blueprint
    api: solver
---
apiVersion: v1
kind: Service
metadata:
  name: gw
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    team: tgedr
    project: microsvc-blueprint
    api: gw
